export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_JOBS_PENDING = 'REQUEST_JOBS_PENDING';
export const REQUEST_JOBS_SUCCESS = 'REQUEST_JOBS_SUCCESS';
export const REQUEST_JOBS_FAILED = 'REQUEST_JOBS_FAILED';